### ISSUE TITLE
Chromium Sushi Browser Architecture not working on Linux. (Debian/Ubuntu)

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [kura52/sushi-browser#67]
As you can see, The chromium window is opened on a separate window of the Sushi Browser UI. However, No interactions between the twos can be done, making it completely none usable.
![Deepin Capture-écran_zone de sélection _20190929101911](https://user-images.githubusercontent.com/13170204/65829174-a148e880-e2a2-11e9-80ab-0cd6a277d9f6.png)
Here´s the only terminal logs i could be gathering from it.
```bash
pm@Velvet4Renaissance:~$ sushi-browser

(sushi-browser:18143): Gtk-WARNING **: 10:19:45.482: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(sushi-browser:18143): Gtk-WARNING **: 10:19:45.482: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(sushi-browser:18143): Gtk-WARNING **: 10:19:45.482: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
/bin/sh: 1: wmctrl: not found
(node:18164) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:18164) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by kura52** [comment]
Thank you for raising this issue.
If wmctrl was not installed, the bundle version of wmctrl was planned to be used, but there was no execution permission.
I fixed it in [v.27.0](https://github.com/kura52/sushi-browser/releases/tag/0.27.0).

**Comment by PoorPocketsMcNewHold** [comment]
Sadly, It seems to still occur, even with wmctrl installed.
Here it is, occuring on deepin with the wmctrl (1.07-7+b1) installed.
![Capture d'écran Deepin_20191020091704](https://user-images.githubusercontent.com/13170204/67156084-776f6880-f31a-11e9-8709-79659bba11b3.png)
```bash
sushi-browser
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
(node:9943) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:9943) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Comment by kura52** [comment]
I am sorry for the late response.

I fixed a bug related to wmctrl in v28.0, so I think it works in gnome, kde, etc., but isn't it still working?

If it doesn't work, can you tell me the version of the Linux distribution?

For issue #69,
I'm not very familiar with i3-gaps, but i3-gaps automatically arranges the windows, so the sushi browser window and the chrome window will be disassembled.
Unfortunately, this is difficult to fix.

**Comment by PoorPocketsMcNewHold** [comment]
It indeed, still doesn´t work.
I´ve this time, tested it in xfce (On Ubuntu Studio).
```bash
            .-/+oossssoo+/-.
        `:+ssssssssssssssssss+:`
      -+ssssssssssssssssssyyssss+-
    .ossssssssssssssssssdMMMNysssso.
   /ssssssssssshdmmNNmmyNMMMMhssssss/
  +ssssssssshmydMMMMMMMNddddyssssssss+     goral@Velvet4Renaissance 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    ------------------------ 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   OS: Ubuntu 19.10 x86_64 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Host: MS-7918 1.0 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Kernel: 5.3.0-21-lowlatency 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Uptime: 1 hour, 50 mins 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Packages: 3667 (dpkg), 14 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.3 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Resolution: 3440x1440 
  +sssssssssdmydMMMMMMMMddddyssssssss+     DE: Xfce 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      WM: Xfwm4 
    .ossssssssssssssssssdMMMNysssso.       WM Theme: Flat-Remix-GTK-Blue-Solid 
      -+sssssssssssssssssyyyssss+-         Theme: Layan-light-solid [GTK2] 
        `:+ssssssssssssssssss+:`           Icons: La-Capitaine [GTK2] 
            .-/+oossssoo+/-.               Terminal: guake 
                                           CPU: Intel i7-4790 (8) @ 4.000GHz 
                                           GPU: NVIDIA GeForce GTX 1060 6GB 
                                           Memory: 21315MiB / 32059MiB 
```

**Comment by kura52** [comment]
Thank you for providing information.

I installed Ubuntu Studio (Eoan Ermine 19.10) on VMware and tried the portable version of sushi-browser, but it worked as shown in the attached image.

Also, it worked with or without wmctrl installed.

I am in trouble because I cannot reproduce the matter.

![Screenshot_20191103_212511](https://user-images.githubusercontent.com/16491181/68085178-704f6b00-fe81-11e9-9638-c24ac902a6ba.png)

**Comment by PoorPocketsMcNewHold** [comment]
![image](https://user-images.githubusercontent.com/13170204/69492783-852a8780-0e9e-11ea-9013-d06a9de95ebf.png)
```bash
                    /-                      pm@Velvet4Renaissance 
                   ooo:                     --------------------- 
                  yoooo/                    OS: ArcoLinuxB-deepin v19.11.3 
                 yooooooo                   Kernel: 5.3.12-arch1-1 
                yooooooooo                  Uptime: 1 hour, 47 mins 
               yooooooooooo                 Packages: 1637 (pacman), 23 (bonsai) 
             .yooooooooooooo                Shell: bash 5.0.11 
            .oooooooooooooooo               Resolution: 3440x1440 
           .oooooooarcoooooooo              DE: Deepin 
          .ooooooooo-oooooooooo             WM: Mutter(DeepinGala) 
         .ooooooooo-  oooooooooo            Theme: Arc-Dark [GTK2], deepin [GTK3] 
        :ooooooooo.    :ooooooooo           Icons: deepin [GTK2/3] 
       :ooooooooo.      :ooooooooo          Terminal: deepin-terminal 
      :oooarcooo         .oooarcooo         Terminal Font: Droid Sans Mono 11 
     :ooooooooy           .ooooooooo        CPU: Intel i7-4790 (8) @ 4.000GHz 
    :ooooooooo   /ooooooooooooooooooo       GPU: NVIDIA GeForce GTX 1060 6GB 
   :ooooooooo      .-ooooooooooooooooo.     Memory: 6768MiB / 32064MiB 
  ooooooooo-             -ooooooooooooo.
 ooooooooo-                 .-oooooooooo.                           
ooooooooo.                     -ooooooooo                           
```
Tested with "wmctrl" installed. (wmctrl-1.07-5).
Used Sushi Browser v0.29.0 Hatahata(Sandfish), the portable version.
Extracted it in my downloads folder, into it's own folder, and just `./sushi-browser` inside. Launched itself separated as showned already. Choose to save automatically, so once clicked, it restarted itself.
I'll test later with a tilling wm, i3 on my notebook but it have a large chance to behave still like this due to tilling nature.

**Comment by PoorPocketsMcNewHold** [comment]
![Capture d’écran du 2019-12-21 11-08-14](https://user-images.githubusercontent.com/13170204/71306573-ff84f380-23d9-11ea-807b-2e9c9c521613.png)
```bash
            -```````````                  pm@vix 
          `-+/------------.`              ------ 
       .---:mNo---------------.           OS: Solus x86_64 
     .-----yMMMy:---------------.         Kernel: 5.3.15-138.current 
   `------oMMMMMm/----------------`       Uptime: 4 hours, 23 mins 
  .------/MMMMMMMN+----------------.      Packages: 1219 (eopkg) 
 .------/NMMMMMMMMm-+/--------------.     Shell: bash 5.0.11 
`------/NMMMMMMMMMN-:mh/-------------`    Resolution: 3440x1440 
.-----/NMMMMMMMMMMM:-+MMd//oso/:-----.    DE: Budgie 
-----/NMMMMMMMMMMMM+--mMMMh::smMmyo:--    Theme: Layan-light [GTK2/3] 
----+NMMMMMMMMMMMMMo--yMMMMNo-:yMMMMd/.   Icons: Papirus-Dark [GTK2/3] 
.--oMMMMMMMMMMMMMMMy--yMMMMMMh:-yMMMy-`   Terminal: guake 
`-sMMMMMMMMMMMMMMMMh--dMMMMMMMd:/Ny+y.    CPU: AMD Ryzen 5 3600X 6- (12) @ 3.800GHz 
`-/+osyhhdmmNNMMMMMm-/MMMMMMMmh+/ohm+     GPU: NVIDIA GeForce GTX 1060 6GB 
  .------------:://+-/++++++oshddys:      Memory: 4507MiB / 32044MiB 
   -hhhhyyyyyyyyyyyhhhhddddhysssso-
    `:ossssssyysssssssssssssssso:`                                
      `:+ssssssssssssssssssss+-                                   
         `-/+ssssssssssso+/-`
              `.-----..`

```
As habitual on the 0.29.1 version, This time on the Budgie Desktop.
wmctrl isn´t installed, and can´t be currently due to not be available in the Solus repository.

**Comment by andika207** [comment]
it doesn't support windows XP. what a shame.
